spring.application.name=vivaeventos-user-service
spring.datasource.url=jdbc:postgresql://postgres:5432/user-db
spring.datasource.username=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
